name: "Code Metrics (On Demand)"

on:
  workflow_dispatch:

jobs:
  analyze:
    name: Run Code Metrics
    runs-on: windows-latest

    permissions:
      contents: read

    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.5'

      - name: Restore dependencies
        run: dotnet restore DataGEMS.Gateway.sln

      - name: Build solution
        run: dotnet build DataGEMS.Gateway.sln --configuration Release --no-incremental

      - name: Check build output size
        run: |
          dir DataGEMS.Gateway.Api/bin/Release/net8.0/
    
      - name: Run code metrics on DataGEMS.Gateway.Api
        run: dotnet msbuild DataGEMS.Gateway.Api/DataGEMS.Gateway.Api.csproj /t:Metrics /p:Configuration=Release /p:TargetFramework=net8.0

#      - name: Run code metrics on DataGEMS.Gateway.App
#        run: dotnet msbuild DataGEMS.Gateway.App/DataGEMS.Gateway.App.csproj /t:Metrics /p:Configuration=Release

#      - name: Run code metrics on DataGEMS.Gateway.Resources
#        run: dotnet msbuild DataGEMS.Gateway.Resources/DataGEMS.Gateway.Resources.csproj /t:Metrics /p:Configuration=Release

      - name: Upload Metrics XML reports
        uses: actions/upload-artifact@v4
        with:
          name: code-metrics-reports
          path: |
            src/DataGEMS.Gateway.Api/DataGEMS.Gateway.Api.Metrics.xml
#            src/DataGEMS.Gateway.App/DataGEMS.Gateway.App.Metrics.xml
#            src/DataGEMS.Gateway.Resources/DataGEMS.Gateway.Resources.Metrics.xml
