name: "Code Metrics (On Demand)"

on:
  workflow_dispatch:

jobs:
  analyze:
    name: Run Code Metrics
    runs-on: ubuntu-latest

    permissions:
      contents: read

    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore DataGEMS.Gateway.sln

      - name: Build solution
        run: dotnet build DataGEMS.Gateway.sln --no-restore --configuration Release

      - name: Run code metrics on DataGEMS.Gateway.Api
        run: dotnet msbuild DataGEMS.Gateway.Api/DataGEMS.Gateway.Api.csproj /t:Metrics

      - name: Run code metrics on DataGEMS.Gateway.App
        run: dotnet msbuild DataGEMS.Gateway.App/DataGEMS.Gateway.App.csproj /t:Metrics

      - name: Run code metrics on DataGEMS.Gateway.Resources
        run: dotnet msbuild DataGEMS.Gateway.Resources/DataGEMS.Gateway.Resources.csproj /t:Metrics

      - name: Upload Metrics XML reports
        uses: actions/upload-artifact@v4
        with:
          name: code-metrics-reports
          path: |
            src/DataGEMS.Gateway.Api/DataGEMS.Gateway.Api.Metrics.xml
            src/DataGEMS.Gateway.App/DataGEMS.Gateway.App.Metrics.xml
            src/DataGEMS.Gateway.Resources/DataGEMS.Gateway.Resources.Metrics.xml
