name: Deploy Docs (On-Demand)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Documentation Version"
        required: true
      set_default:
        description: "Set as default version"
        required: false
        default: "true"
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    defaults:
      run:
        working-directory: docs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mike

      - name: Configure git for mike
        run: |
          git config user.name "datagems-ci[bot]"
          git config user.email "datagems-ci[bot]@datagems.eu"

      - name: Fetch existing gh-pages branch
        run: git fetch origin gh-pages:gh-pages

      - name: Deploy versioned docs with mike
        run: mike deploy ${{ github.event.inputs.version }} --push --config-file mkdocs.yml

      - name: Set default version
        if: ${{ github.event.inputs.set_default == "true" }}
        run: mike set-default ${{ github.event.inputs.version }} --push --config-file mkdocs.yml
